# Generated by Django 4.1.5 on 2023-02-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="pic2",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="Pics"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="pic3",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="Pics"
            ),
        ),
    ]
