# Generated by Django 4.1.5 on 2023-02-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_product_pic2_product_pic3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discription",
            field=models.TextField(max_length=100),
        ),
    ]
