# Generated by Django 4.1.5 on 2023-02-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_alter_product_discription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discription",
            field=models.TextField(),
        ),
    ]
