# Generated by Django 4.1.5 on 2023-02-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_alter_product_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.CharField(max_length=15),
        ),
    ]
